### ISSUE TITLE
Implementa una galeria de imagenes

### ISSUE THREAD

**Issue by QITO17** [QITO17/proy_esteban#5]
Deberas implementar una galeria de imagenes  en las cuales se vean las tecnologías usadas en el proyecto como CSS, HTML, JS y github debera tener un titulo que diga tecnologías usadas, ademas de eso en la pagina aparece contacto en una parte de arriba del codigo 
![image](https://github.com/user-attachments/assets/bba4628e-a88f-4633-acc7-4b0088eec6bb)

la cual deberas poner abajo en el footer de la pagína y las fuentes de letra donde muestras los ejemplos de git deben ser blancas.

**Comment by EstebanDuarte19** [comment]
Se realizo el cambio en la parte de contacto ya se encuentra en el footer
